Add PACMI'24 workshop paper publication
cloudflare/research.cloudflare.com pull request #152
Opened 2024-11-19 21:00 UTC by SulemanAhmadd

Additionally adds new interest field for "Machine Learning".

2024-11-20 10:33 UTC, vgonc requested changes
doi url returns not found. I couldn't find the paper or the correct doi elsewhere,

2024-11-20 15:45 UTC, SulemanAhmadd commented
Ah. Seems like the venue still has to make the document public :( We can wait.

2024-12-30 20:09 UTC, SulemanAhmadd commented
DOI URL is now live: https://dl.acm.org/doi/10.1145/3704742.3704962

2024-12-31 09:37 UTC, vgonc approved these changes

2024-12-31 09:37 UTC, merged